version: '3.2'

services:
  app:
    image: ghcr.io/mamura/php81-fpm:latest
    labels:
      - traefik.http.routers.app.rule=Host(`app.mamura.test`)
    volumes:
      - ./src:/src
    environment:
      - PROJECT_WEBROOT=/src/public

networks:
  default:
    external:
      name: dev-network